---
- hosts: all
  gather_facts: yes
  become: true
  roles:
    - developer
    - role: gantsign.visual-studio-code
      users:
        - username: devel
          visual_studio_code_extensions:
            - yzhang.markdown-all-in-one
            - shd101wyy.markdown-preview-enhanced
            - davidanson.vscode-markdownlint