---
#node version is incompatible, so we install the current node LTS version instead
- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

# install dev tools
- name: Install dev tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git-core
    - gitk
    - gcc-multilib
    - build-essential
    - clang-format
    - make
    - gcc
    - build-essential
    - g++
    - python-dev
    - autotools-dev
    - libicu-dev
    - build-essential
    - libbz2-dev
    - openssl
    - libcurl4-openssl-dev
    - uuid-dev
    - meld
    - libssl-dev
    - nodejs
    - doxygen

#Configure meld as default mege tool
- git_config:
    name: merge.tool
    scope: global
    value: meld

- name: Install "diff-so-fancy" node.js package globally.
  npm:
    name: diff-so-fancy
    global: yes

# Configure "diff-so-fancy"
- git_config:
    name: core.pager 
    scope: global
    value: "diff-so-fancy | less --tabs=4 -RFX"
- git_config:
    name: color.ui 
    scope: global
    value: true
- git_config:
    name: color.diff-highlight.oldNormal
    scope: global
    value: "red bold"
- git_config:
    name: color.diff-highlight.oldHighlight
    scope: global
    value: "red bold 52"
- git_config:
    name: color.diff-highlight.newNormal
    scope: global
    value: "green bold"
- git_config:
    name: color.diff-highlight.newHighlight
    scope: global
    value: "green bold 52"
- git_config:
    name: color.diff.meta
    scope: global
    value: "yellow"
- git_config:
    name: color.diff.frag  
    scope: global
    value: "magenta bold"
- git_config:
    name: color.diff.commit 
    scope: global
    value: "yellow bold"
- git_config:
    name: color.diff.old 
    scope: global
    value: "red bold"
- git_config:
    name: color.diff.new 
    scope: global
    value: "green bold"
- git_config:
    name: color.diff.whitespace
    scope: global
    value: "red reverse"